//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public string Foodtype { get; set; }
        public int PreservationHour { get; set; }
        public int PacketCount { get; set; }
        public int RID { get; set; }
        public Nullable<int> Assign { get; set; }
        public int Status { get; set; }
    
        public virtual LogIninfo LogIninfo { get; set; }
    }
}
