//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestuarentInfo
    {
        public int SerialNo { get; set; }
        public string RestuarantName { get; set; }
        public string Address { get; set; }
        public string OwnerName { get; set; }
        public int ID { get; set; }
    
        public virtual LogIninfo LogIninfo { get; set; }
    }
}
