//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zero_HungerEntities : DbContext
    {
        public Zero_HungerEntities()
            : base("name=Zero_HungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminStaffInfo> AdminStaffInfoes { get; set; }
        public virtual DbSet<LogIninfo> LogIninfoes { get; set; }
        public virtual DbSet<RestuarentInfo> RestuarentInfoes { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
    }
}
